Add scrapers to pull Budget data from OMB
stevesdawg/govstat pull request #29
Opened 2022-07-18 03:36 UTC by connorjoleary

closes #15

2022-07-19 21:24 UTC, acxz commented
whoa this is amazing, thx for the contribution @connorjoleary . I'm gonna take a look at this later today or tomorrow and test it out. We're excited you want to help out on this little project!

btw if you plan on continuing to contribute we can get into a call or something so that we can make a little roadmap for this project

2022-07-19 21:25 UTC, connorjoleary commented
Sounds great to me!

2022-07-21 03:36 UTC, stevesdawg commented
@connorjoleary wow, thank you for contributing!

A clean solution to this problem. I'll test this in my server environment this weekend and give some feedback. Thanks again.

2022-07-30 19:33 UTC, connorjoleary commented
Thank you guys for the kind words. I'd be happy to meet with you and discuss where you see this going and what I can do to help. My email is connor.oleary24@gmail.com if you want to reach out and set up a time to chat. I'm also working on a project analysing what members of Congress say during congressional hearing and I'd be happy to somehow incorporate that into this project.

2022-08-06 14:06 UTC, acxz approved these changes
Just tested the script, it works wonderfully.

We will need to have some follow up commits to
- use the newly named directory
- remove the existing data and the git-lfs dep

But on its own this is a nice atomic commit.

@stevesdawg LGTM

2022-08-07 22:20 UTC, stevesdawg commented on setup.py
> +        "requests",
A nitpick, remove this line as we already list `requests` as a dep.

2022-08-07 22:30 UTC, stevesdawg requested changes
Tiny nitpick change requested, but otherwise, this looks good to me! Thanks for the great feature. I will rebase and merge once you follow up.

2022-08-07 22:54 UTC, acxz commented
> My email is [connor.oleary24@gmail.com](mailto:connor.oleary24@gmail.com) if you want to reach out and set up a time to chat.

Do you have a [matrix](https://matrix.org/) account? We can much easily communicate on there instead of an email back and forth. My UN is https://matrix.to/#/@1awtumleef:matrix.org feel free to contact me.

2022-08-07 22:56 UTC, stevesdawg approved these changes

2022-08-07 22:56 UTC, merged

2022-08-07 23:05 UTC, stevesdawg commented
Added the fix myself, and merged your code in @connorjoleary 🚀